project:
  type: website

website:
  title: "Home"
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    title: Jie Wang
    right:
      - href: blog/index.qmd
    tools:
      - icon: github
        href: https://github.com/ifendo
format:
  html:
    fontsize: 20px
    theme: [cosmo, styles.scss]
